sonar.projectKey=logs-system
sonar.projectName=logs-system
sonar.host.url=http://localhost:9000
sonar.login=sqp_1082a241156bffc018595ca86926114506f84f80

sonar.sources=src
sonar.language=ts

sonar.exclusions=node_modules/**,dist/**